version: "3.9"

services:
  bot:
    build: .
    container_name: fingames_bot
    restart: always
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: fingames_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
